# Generated by Django 2.2.4 on 2021-03-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login_app', '0003_auto_20210324_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='Login_app.User')),
                ('users_joined', models.ManyToManyField(related_name='jobs_joined', to='Login_app.User')),
            ],
        ),
    ]
