# Generated by Django 2.2.4 on 2021-03-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0002_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
